### ISSUE TITLE
[DOC] Add a minimal README to present the project and the first features

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bv-experimental-add-ons#21]
General #25
- [x] Update content and repository description to match #5 
- [x] Add a license paragraph

Usage #25
- [x] How to install with npm and bpmn-visualization dependency

Release how-to #43
- [x] how to handle the npm publish #7
- [x] how to create the GitHub release and/or changelog file

`BpmnElementsSearcher` #25
- [x] describe initial use cases covered and why (see description in https://github.com/process-analytics/bpmn-visualization-js/issues/2453)
- [x] mention limitations

`PathResolver` #25
- [x] describe initial use cases covered and why
- [x] frontend processing, probably more efficient if done in backend. Workaround the limitation of the tools and algorithms provided in backend
