### ISSUE TITLE
[FEAT] Provide an IIFE bundle in the npm package

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bv-experimental-add-ons#26]
**Is your feature request related to a problem? Please describe.**
The first version of the npm package only provide ES modules, so I cannot evaluate the add-ons directly in my browser along with `bpmn-visualization`

**Describe the solution you'd like**
Create the bundle with the bundler of your choice. In `bpmn-visualization`, we use **_Rollup_**. We may reuse it to capitalize.

**⚠️ WARNING ⚠️** bpmn-visualization (and its implementation) must not be integrated in the bundles. HTML pages will load it by themself. Remember that the code of bpmn-visualization is available as a global `bpmnVisu` object, so the produced IIFE bundle should use this global object. https://rollupjs.org/configuration-options/#output-globals may help.

```[tasklist]
### Tasks
- [ ] Add build script to create the bundle
- [ ] Include the bundle in the package
- [ ] Choose a name for the global variable representing the bundle (for instance bvAddons)
- [ ] Test the produced bundle in an HTML page. We could add a new workspace to handle the automatic tests
- [ ] README: document how to use the IIFE bundle
- [ ] README: warn users about the potential size of the bundle that cannot be tree-shaked. It includes all add-ons. In the future, there will be plenty with various variants.
```

**Comment by tbouffard** [comment]
We have decided not to pursue this feature. The main objective of this library is to experiment with ways to enhance tree-shaking for `bpmn-visualization` by offering tree-shakable features. Providing an IIFE bundle does not align with this goal.

So closing this issue.
