### ISSUE TITLE
[INFRA] Automate the generation of the GitHub release drafts

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bv-experimental-add-ons#39]
This is currently done manually and is error prone. We have to follow a procedure described in the README.
We could use a GitHub workflow to create a draft release when a new tag is published.

**NOTE**: this is very closed to https://github.com/process-analytics/bpmn-visualization-examples/issues/375

```[tasklist]
### Tasks
- [x] Test an implementation in the playground repository. See https://github.com/process-analytics/github-actions-playground/pull/311#issuecomment-1880489125
- [ ] Implementation in this repository
- [ ] Update the release paragraph in the README
```
