### ISSUE TITLE
[INFRA] Setup test infrastructure

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bv-experimental-add-ons#65]
This is required prior moving forward with new features.
We already need it for:
- #3 
- #18 
- testing plugins

We could use ts-jest and jest-jsdom as done in `bpmn-visualization`.
Interesting alternatives could be evaluated as well
- ava as test runner
  - IntelliJ/Webstorm plugin exists: https://plugins.jetbrains.com/plugin/13835-ava-test-run-configuration-generator. If we use it, document it in the installation step
  - VSCode: https://github.com/avajs/ava/blob/main/docs/recipes/debugging-with-vscode.md
- https://testing-library.com/ and DOM testing: https://testing-library.com/docs/dom-testing-library/intro

### Decisions

Based on various POC, we will use jest and ts-jest. See
- #81
- #82 
- #95
- #96

We already use this infrastructure in bpmn-visualization, so this will also ease the move of implementation and tests between the 2 projects.

```[tasklist]
### Tasks to setup ts-jest
- [x] Use #96 as a starting point
- [x] Migrate all existing JavaScript tests to TypeScript
- [x] Verify "module" settings in the dedicated tsconfig.json file used in tests: Keep values from the tsconfig file used to transpile addons sources.
- [x] Dedicated tsconfig.json file used in tests. Enable sourceMap and verify that tests can be debugged. With js tests, the lib must built with ` tsc --watch --sourceMap` to debug tests
- [x] jest config: make type guidance work in IDE for ts-jest (adapt existing type)
- [x] jest config. According to https://jestjs.io/docs/configuration#modulefileextensions-arraystring, the ts extension should be set at the first place - "We recommend placing the extensions most commonly used in your project on the left"
- [x] Update the dependabot config to add new jest dependencies to the jest group
```

About _Verify "module" settings in the dedicated tsconfig.json file used in tests_ task
- check if we need to use node16 or nodeNext, ES2021 or ESNext. See
  - https://www.typescriptlang.org/docs/handbook/esm-node.html
  - https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm 
  - https://github.com/sindresorhus/tsconfig/blob/main/tsconfig.json. 
- Only required to be able to handle `mts` files and we are not using such extension. (https://kulshekhar.github.io/ts-jest/docs/guides/esm-support#support-mts-extension)

Resources that may help to setup `ts-jest`:
- https://www.typescriptlang.org/tsconfig#module
- https://www.typescriptlang.org/docs/handbook/module-resolution.html#using---noresolve
- https://www.typescriptlang.org/docs/handbook/esm-node.html
- https://www.typescriptlang.org/docs/handbook/modules.html
- debugging ts-jest: https://kulshekhar.github.io/ts-jest/docs/debugging
