### ISSUE TITLE
[BUG] PathResolver demo: additional non-selected shapes and incorrect path displayed

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bv-experimental-add-ons#67]
**Describe the bug**
When selecting a set of elements and clicking on the "Compute path" button, the edge are correctly computed and highlighted.
Then, after selecting other elements, the previously computed edges stay highlighted.

**To Reproduce**

Go to the `PathResolver` demo and perform actions as in the following video 👇🏿

https://github.com/process-analytics/bv-experimental-add-ons/assets/27200110/2342eb4f-5fe5-4bdc-926d-2f9b44545bf7

**Expected behavior**
The selected shapes should stay selected.

**Screenshots**
See ☝🏿.

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all

**Additional context**
This is a bug in `bpmn-visualization` and a workaround as been added to the demo to temporarily fix the problem.

https://github.com/process-analytics/bv-experimental-add-ons/blob/6c552111219f0abd87c93cf65d08ae55e1757c69/packages/demo/src/path-resolver.ts#L44-L48

### Root cause of the problem

The issue is in `BpmnElementsRegistry.resetStyle` which treats empty array as undefined and in this case, resets the style of all elements.

Convert `undefined` into an empty array

https://github.com/process-analytics/bpmn-visualization-js/blob/3d36ba70708be4fdc8a4e6242ac2e840758a33f0/src/component/registry/bpmn-elements-registry.ts#L382-L384

Empty array --> reset the style of all elements.

https://github.com/process-analytics/bpmn-visualization-js/blob/3d36ba70708be4fdc8a4e6242ac2e840758a33f0/src/component/mxgraph/GraphCellUpdater.ts#L121-L130

Here is the implementation of `BpmnElementsRegistry.removeAllCssClasses`

https://github.com/process-analytics/bpmn-visualization-js/blob/3d36ba70708be4fdc8a4e6242ac2e840758a33f0/src/component/registry/bpmn-elements-registry.ts#L205-L216

**_TODO explain the root cause_**

```[tasklist]
### Tasks
- [x] Fix the issue in `bpmn-visualization`. https://github.com/process-analytics/bpmn-visualization-js/pull/2798
- [x] Add tests to validate in all reset methods of `BpmnElementsRegistry` that passing an empty array has no effect
- [x] Add tests to validate in all reset methods of `BpmnElementsRegistry` that passing a _nullish_ parameter (null or undefined) reset all
- [x] Update the JSDoc of the `resetStyle` method to clarify that nothing happens when passing an empty array and that the reset is done when passing a _nullish_ parameter.
- [x] Review the JSDoc of other `reset` methods to be consistent
- [x] Integrate a released version of `bpmn-visualization` including the fix: https://github.com/process-analytics/bpmn-visualization-js/releases/tag/v0.38.1
- [x] Remove the workaround in the `PathResolver` demo
```
