### ISSUE TITLE
[INFRA] Prepare the npm package

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bv-experimental-add-ons#7]
```[tasklist]
### Tasks
- [x] mandatory: #6
- [x] review the package.json file: keywords, files, exports, main, .... #42
- [x] provide ESM, and types
- [x] create a GitHub Actions workflow to automate the publishing. We may act like in the bpmn-visualization: one wf to create the tag and update content, one workflow to perform the npm publish. Be aware of branch protection that may use https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets
- [x] .npmrc or GH workflow: configure "access=public" to publish the package as "scoped". See https://docs.npmjs.com/cli/v9/commands/npm-publish#access. Configuring the value in the configuration file will avoid to configure it in the workflow and make things explicit.
- [x] ensure that the "npm provenance" is configured (workflow or .npmrc). https://docs.npmjs.com/cli/v9/commands/npm-publish?v=true#provenance
- [x] include license in the package
- [x] include README
- [x] check that secrets are available
- [x] update the release procedure in the README #43
```
