### ISSUE TITLE
[INFRA] Setup SonarCloud

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bv-experimental-add-ons#9]
If no specific configuration is required, configure it on the SonarCloud side instead of in a GitHub workflow.

```[tasklist]
### Tasks
- [x] setup automatic analysis
- [x] add a badge in the README #69
- [x] verify that analysis is done when creating a new PR #69
```

![image](https://github.com/process-analytics/bv-experimental-add-ons/assets/27200110/1ad04d75-86cb-4d46-a879-1dc44a4dc6a2)
