### ISSUE TITLE
[INFRA] Remove the patch of the bpmn-visualization package.json when version `0.39.0` is available

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bv-experimental-add-ons#97]
This patch has been configured to make jest tests work. See #100.
`bpmn-visualization` will be fixed once https://github.com/process-analytics/bpmn-visualization-js/pull/2840 has been merged and released.

```[tasklist]
### Tasks
- [ ] Use bpmn-visualization 0.39.0
- [ ] Remove the patch script and resources (patch file, package.json script)
- [ ] Restore the --ignore-scripts in "build-setup" GitHub action (patch previously applied via a postinstall script)
```
